[package]
name = "lightyear_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true


[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
serde = { version = "1.0.188", features = ["derive"] }
anyhow = "1.0.75"
darling = "0.20"



[dev-dependencies]
lightyear_shared = { path = ".." }
enum-as-inner = "0.6.0"
bevy = { version = "0.12", default-features = false }
enum_delegate = "0.2"
derive_more = { version = "0.99", features = ["add", "mul"] }
bitcode = { git = "https://github.com/cBournhonesque/bitcode.git", branch = "cb/latest", features = ["serde"] }



