[target.x86_64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes pkg-config:$CROSS_DEB_ARCH libssl-dev:$CROSS_DEB_ARCH ca-certificates:$CROSS_DEB_ARCH libasound2-dev:$CROSS_DEB_ARCH libpulse-dev:$CROSS_DEB_ARCH libdbus-1-dev:$CROSS_DEB_ARCH portaudio19-dev:$CROSS_DEB_ARCH libudev-dev:$CROSS_DEB_ARCH"
]