[book]
authors = ["Charles Bournhonesque"]
language = "en"
multilingual = false
src = "src"
title = "Lightyear cheatbook"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
site-url = "/book/"

[output.linkcheck]